export { default as HomePage } from "./Home";
export { default as ProductsPage } from "./Products";
export { default as ProductDetailPage } from "./ProductDetail";
export { default as CartPage } from "./Cart";
export { default as CheckoutPage } from "./Checkout";
export { default as LoginPage } from "./Login";
export { default as RegisterPage } from "./Register";
export { default as OrdersPage } from "./Orders";
export { default as WishlistPage } from "./Wishlist";
