export { DashboardTab as InventoryDashboardTab } from "./InventoryDashboardTab";
export { OrdersTab as InventoryOrdersTab } from "./InventoryOrdersTab";
export { ProductsTab as InventoryProductsTab } from "./InventoryProductsTab";
export { InventoryReturnsTab } from "./InventoryReturnsTab";
export { SettingsTab as InventorySettingsTab } from "./InventorySettingsTab";
export { ExportReportsCard } from "./ExportReportsCard";
export { ReturnsAnalyticsCard } from "./ReturnsAnalyticsCard";
export { SalesTrendsChart } from "./SalesTrendsChart";
export { TopProductsChart } from "./TopProductsChart";
export { ProductAllocationForm } from "./ProductAllocationForm";
